### ISSUE TITLE
VS 2020 works -  but error "Could not load file or assembly 'EntityFramework'"

### ISSUE THREAD

**Issue by klacol** [msawczyn/EFDesigner2022#1]
Hi, nice project here. It looks very promising, especially the posilbity to set (domain-specific-)views over the complete model. I try to get it working with our model. I see two approaches:

1.  Generate the .efmodel file from our internal configuration, which holds most of this infomation
2. Generate the .efmodel file from the database model
3. Generate it from the dll

I started with the third option. Our dll ist compiled against the ,NET Framework 4.6.1 with Entity Framework 6.1.3.

Unfortunately I see always this:

> Could not load file or assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified

I did the following, after installing the Extension:

1. Setup a new library project in VS 2022 for .NET Framework 4.6.1.
2. Added Entity Framework  6.1.3
3. Added an EF Visual Editor
4. Dropped the dll on the Editor

What am I missing here? Any hint is appreciated.

**Comment by msawczyn** [comment]
Not sure. That should work. Will look into it. Thanks for the report!

**Comment by msawczyn** [comment]
Found an issue regarding detection of inherited classes that may have contributed to this and fixed it. If you're still seeing this problem, ensure that all the needed dependencies are either in the same directory of the assembly you're consuming or in the GAC. If they are and you're still seeing this, please let me know.
