### ISSUE TITLE
Release 4.1.2 VSIX fails to update in VS 2022 | Win 11

### ISSUE THREAD

**Issue by IoTFier** [msawczyn/EFDesigner2022#10]
Hello @msawczyn 

I tried upgrading VS 2022 extension to the latest version of 4.1.2. 
But it is failing to upgrade with the error details shown below.
Your help will be appreciated.
Thank you.

![image](https://user-images.githubusercontent.com/26844611/154802358-8c6b3e98-1358-48a9-88f0-75cec3df9ce4.png)

2/19/2022 7:09:36 AM - Microsoft VSIX Installer
2/19/2022 7:09:36 AM - -------------------------------------------
2/19/2022 7:09:36 AM - vsixinstaller.exe version:
2/19/2022 7:09:36 AM - 17.2.37-preview1
2/19/2022 7:09:36 AM - -------------------------------------------
2/19/2022 7:09:36 AM - Command line parameters:
2/19/2022 7:09:36 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe,/skuName:Pro,/skuVersion:17.1.32210.238,/appidname:Microsoft Visual Studio Professional 2022,/culture:en-US,/noep,C:\Users\ ******\AppData\Local\Temp\VSIX0rva2ozn.vsix,/callingprocessid:9736,/installas:3976
2/19/2022 7:09:36 AM - -------------------------------------------
2/19/2022 7:09:36 AM - Microsoft VSIX Installer
2/19/2022 7:09:36 AM - -------------------------------------------
2/19/2022 7:09:36 AM - Skipping product Microsoft.VisualStudio.Product.BuildTools (b54b4f41) since it does not support extensions
2/19/2022 7:09:36 AM - Skipping product Microsoft.VisualStudio.Product.BuildTools (fa3960c2) since it does not support extensions
2/19/2022 7:09:36 AM - Initializing Install...
2/19/2022 7:09:36 AM - Extension Details...
2/19/2022 7:09:36 AM - 	Identifier         : dd1c2ec0-b732-4b74-a591-4d78684bb231
2/19/2022 7:09:36 AM - 	Name               : Entity Framework Visual Editor
2/19/2022 7:09:36 AM - 	Author             : Michael Sawczyn
2/19/2022 7:09:36 AM - 	Version            : 4.1.2.0
2/19/2022 7:09:36 AM - 	Description        : Entity Framework visual editor for EF6, EFCore and beyond.
2/19/2022 7:09:36 AM - 	Locale             : en-US
2/19/2022 7:09:36 AM - 	MoreInfoURL        : 
2/19/2022 7:09:36 AM - 	InstalledByMSI     : False
2/19/2022 7:09:36 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
2/19/2022 7:09:36 AM - 
2/19/2022 7:09:36 AM - 	SignatureState     : Unsigned
2/19/2022 7:09:36 AM - 	Supported Products : 
2/19/2022 7:09:36 AM - 		Microsoft.VisualStudio.Community
2/19/2022 7:09:36 AM - 			Version : [17.0,18.0)
2/19/2022 7:09:36 AM - 			ProductArchitecture : amd64
2/19/2022 7:09:36 AM - 
2/19/2022 7:09:36 AM - 	References         : 
2/19/2022 7:09:36 AM - 		-------------------------------------------------------
2/19/2022 7:09:36 AM - 		Identifier   : Microsoft.VisualStudio.MPF.17.0
2/19/2022 7:09:36 AM - 		Name         : Visual Studio MPF 17.0
2/19/2022 7:09:36 AM - 		Version      : [17.0,18.0)
2/19/2022 7:09:36 AM - 		MoreInfoURL  : 
2/19/2022 7:09:36 AM - 		Nested       : No
2/19/2022 7:09:36 AM - 
2/19/2022 7:09:36 AM - 	Prerequisites      : 
2/19/2022 7:09:36 AM - 		-------------------------------------------------------
2/19/2022 7:09:36 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2/19/2022 7:09:36 AM - 		Name         : Visual Studio core editor
2/19/2022 7:09:36 AM - 		Version      : [17.0,18.0)
2/19/2022 7:09:36 AM - 
2/19/2022 7:09:36 AM - Signature Details...
2/19/2022 7:09:36 AM - 	Extension is not signed.

**Comment by msawczyn** [comment]
Unfortunately, I haven't been able to reproduce the problem you're seeing. The messages indicate that the VSIX isn't signed, and that's correct, but it's not a Visual Studio requirement that packages be signed before installing. The designer hasn't ever been signed; if you've been able to install it before, nothing's changed in this regard for v4.1.2

I'd suggest re-downloading it from the Marketplace and trying again. There may have been an issue with the download.

**Comment by IoTFier** [comment]
Hi @msawczyn, I uninstalled the extension and followed your instructions. It worked. So, closing this issue for now.
Thank you for your help.
