### ISSUE TITLE
Visual Studio 2022 for MAC support

### ISSUE THREAD

**Issue by mihaimarin83** [msawczyn/EFDesigner2022#11]

**Comment by msawczyn** [comment]
Unfortunately, I don't own (nor do I plan to own) a Mac, and that's required to compile programs that will run on a Mac.

That's not to say that someone else may take this request under their wing and write an extension for that platform. Although I do know that the extension ecosystem on VS-Mac isn't quite up to what it is on VS-Win.

Closing.

**Comment by virajkanwade** [comment]
Sorry to respond on a closed issue, but didn't want to clutter. Also easier if everything is kept in one place so tomorrow if you decide to, you could refer these findings.

I tried to load the code in VS2022Mac. Except for Dsl and DslPackage projects, all other projects seemed to load fine. For both Dsl.csproj and DslPackage.proj, replacing 
```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="17.0">
```
with
```
<Project Sdk="Microsoft.NET.Sdk">
```
loaded the projects. I checked EFCore7Parser.csproj and it had `<Project Sdk="Microsoft.NET.Sdk">`. So my guess is you need to update Dsl and DslPackage to new versions of VS?

Also, after the projects loaded, DslPackage had a warning that this project is not supported in VS2022Mac Community Edition.

**Comment by virajkanwade** [comment]
This line seems to be the major issue:

`<Import Project="$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)\DSLTools\Microsoft.DslTools.settings.targets" />`

I could not find DSLTools anywhere on the Mac.

From the documentation it seems it is part of
Build Tools for Visual Studio 2022
These Build Tools allow you to build Visual Studio projects from a command-line interface. Supported projects include: ASP.NET, Azure, C++ desktop, ClickOnce, containers, .NET Core, .NET Desktop, Node.js, Office and SharePoint, Python, TypeScript, Unit Tests, UWP, WCF, and Xamarin. Use of this tool requires a valid Visual Studio license.

This seems to be Windows only.

**Comment by msawczyn** [comment]
> This seems to be Windows only.

I believe it is. It's installed by default now with Visual Studio 2022 rather than as part of the VS SDK, but is complex enough (and old enough) that it hasn't been retooled for the libraries used by VS Mac.

DSL tools, once you dig into it (and so few do) is a masterful piece of work. Has its own patent. Lightly maintained by MS, but there really isn't much that needs done with it (seems that when modernization changes are made, they take a few iterations to clean out the bugs they introduced).
