### ISSUE TITLE
Foreign Keys on the generated constructor

### ISSUE THREAD

**Issue by danisss9** [msawczyn/EFDesigner2022#21]
**Problem:**

I have a table City which has a 1..N association with Country (Allow Foreign Keys option is enabled).

![image](https://user-images.githubusercontent.com/36733433/168258156-8064dc0f-bec1-44b1-8714-f2638bcca5d4.png)

When EFDesigner generates the class the constructor of the class is including the foreign keys fields.

![image](https://user-images.githubusercontent.com/36733433/168258632-93582824-9329-475b-ad81-6afe713bf24e.png)

**Proposed behavior:**

EFDesigner should not include foreign keys in the generated constructor, only the associative objects. (better if have an option to enable/disable this).

![image](https://user-images.githubusercontent.com/36733433/168259240-551b1d9f-9e58-46f1-a7a0-9ae200b70776.png)

**Current behavior:**
Both foreign keys and associative objects are in the constructor.

Versions
EF Visual Editor: 4.1.2.0
Visual Studio 2022: 17.1.6

**Comment by msawczyn** [comment]
This is something I've been meaning to do for quite some time now.
