### ISSUE TITLE
Looks like you are taking a break from the project

### ISSUE THREAD

**Issue by dcastenholz** [msawczyn/EFDesigner2022#22]
Michael,

Are you expecting to continue with it soon?

Daniel

**Comment by MichaelSawczyn-AWH** [comment]
Hi Daniel,

Yes, soon. Work and life have been getting in the way :-) Should be able to get things done here shortly.

**Comment by msawczyn** [comment]
Hi Daniel,

Yes, soon. Work and life have been getting in the way :-) Should be able to get things done here shortly.
