### ISSUE TITLE
OnDelete is missing on output

### ISSUE THREAD

**Issue by slargollo** [msawczyn/EFDesigner2022#24]
When using EFCore5ModelGenerator and SourceMultiplicity is One or ZeroOne, OnDelete is not being generating.
I've had to change the method WriteBidirectionalNonDependentAssociations to corrected that:

                  case Sawczyn.EFDesigner.EFModel.Multiplicity.One:
                  case Sawczyn.EFDesigner.EFModel.Multiplicity.ZeroOne:
                     segments.Add($"WithOne(p => p.{association.SourcePropertyName})");
                     // Force output of OnDelete
                     **WriteSourceDeleteBehavior(association, segments);**
                     break;

**Comment by msawczyn** [comment]
Thanks for the catch. The fix will be in the next release.
