### ISSUE TITLE
Missing ForaignKey on 1 <-> 0..1

### ISSUE THREAD

**Issue by Mr-Pearce** [msawczyn/EFDesigner2022#25]
Unchanged
![grafik](https://user-images.githubusercontent.com/13457314/183638622-9818aee0-74a7-4061-bd8c-f7ef0794d431.png)

**Created DbContext Code:**
v4.0.1.0
```
modelBuilder.Entity<Upload>()
		 .HasOne<Commit>(p => p.Commit)
		 .WithOne(p => p.Upload)
		 .HasForeignKey("Commit", "UploadId")
		 .OnDelete(DeleteBehavior.Cascade);
```
v4.1.2.0
```
modelBuilder.Entity<Upload>()
			 .HasOne<Commit>(p => p.Commit)
			 .WithOne(p => p.Upload);
```
Error v4.1.2.0
```
System.InvalidOperationException: The dependent side could not be determined for the one-to-one relationship between 'Commit.Upload' and 'Upload.Commit'. 
To identify the dependent side of the relationship, configure the foreign key property. If these navigations should not be part of the same relationship, configure them independently via separate method chains in 'OnModelCreating'. See http://go.microsoft.com/fwlink/?LinkId=724062 for more details.
```

When i ad the missing two lines back it works like before.

Working but still strange
![grafik](https://user-images.githubusercontent.com/13457314/183640680-3af75003-f78c-41fb-ab53-b216dc646f56.png)

v4.0.1.0
```
modelBuilder.Entity<Program>()
		 .HasMany<Upload>(p => p.Uploads)
		 .WithOne(p => p.Program)
		 .HasForeignKey("ProgramId")
		 .OnDelete(DeleteBehavior.NoAction)
		 .IsRequired();
```
v4.1.2.0
```
modelBuilder.Entity<Program>()
		 .HasMany<Upload>(p => p.Uploads)
		 .WithOne(p => p.Program);
```

Is this behavior expected?

**Comment by msawczyn** [comment]
Using the latest version (4.2.0) I made the following model:
![image](https://user-images.githubusercontent.com/1778442/184533101-ab527831-f71f-469b-b230-0c0dee31be87.png)

It generated the code
```
         modelBuilder.Entity<global::EFVisualEditorTest.Child>()
                     .ToTable("Child")
                     .HasKey(t => t.ID);
         modelBuilder.Entity<global::EFVisualEditorTest.Child>()
                     .Property(t => t.ID)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::EFVisualEditorTest.Child>()
                     .Property(t => t.PID)
                     .IsRequired();
         modelBuilder.Entity<global::EFVisualEditorTest.Child>().HasIndex(t => t.PID);

         modelBuilder.Entity<global::EFVisualEditorTest.Parent>()
                     .ToTable("Parent")
                     .HasKey(t => t.ID);
         modelBuilder.Entity<global::EFVisualEditorTest.Parent>()
                     .Property(t => t.ID)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::EFVisualEditorTest.Parent>()
                     .HasOne<global::EFVisualEditorTest.Child>(p => p.Child)
                     .WithOne(p => p.Parent)
                     .HasForeignKey<global::EFVisualEditorTest.Child>(k => k.PID);
```
which migrated fine and created the database.

Possibly the issue slipped by in a prior version but is fixed now. Can you give it another try?

**Comment by Mr-Pearce** [comment]
The Entities above are fine now.
But i found another "inconsistency"
Bidirectinal Associations generate different code depending on the Start and End point even when you set the Multiplicity the same. 
Although it looks identical in the Model Diagram.

Left: Bidirectional from Upload -> Release
Right: Bidirectional from Release -> Upload with switched Multiplicity
It looks nearly the same in the Model Diagram, shouldn't this create identical `modelBuilder `Code? 

![grafik](https://user-images.githubusercontent.com/13457314/184816422-df3be5b7-19e8-4881-af2f-eb482309abb4.png)

**Comment by msawczyn** [comment]
That's a side effect of how the T4 iterates through the classes. The resulting code is functionally identical, ignoring the change resulting from the removal in the model of the `UploadId` foreign key property. There isn't a need to change what it does since it produces the same model in Entity Framework Core.

Of course, since this processing happens in the T4, you're free to change it if it's bothersome. But it doesn't worry me from a product functionality standpoint.

Thanks for pointing it out. Since the original issue is resolved, I'll close this ticket.
