### ISSUE TITLE
Help: Importing entities from C# source

### ISSUE THREAD

**Issue by fasteddys** [msawczyn/EFDesigner2022#27]
Hello, I am very impressed with your features, I wanted to share while the install succeeded, it hangs, I had to restart VS to make it work after clearing the MEF cache.

I saw this feature -
_..._importing entities from C# source_, or existing DbContext definitions (including their entities) from compiled EF6 or EFCore assemblies"_

Can I please ask for some help here, we have projects where I am trying your tool to upgrade into EF core. In the previous version, they used `Models/Entities` , `ADO `with `SP's/StoreProcs`. 

_Inside_ the `model `namespace, since we have all/list all the code/objects/entities/models without a DB context, can you add some help on `how to import those source/entities to the designer ` is it done by these methods, I apologize I was reading the help and could not figure it out.

- [ ] by drag and drop 
- [ ] or right click import namespace
- [ ] or right click import the models/entities in the solution tree

**Comment by msawczyn** [comment]
If you don't have a compiled assembly that already has a DbContext, your best bet is to drag/drop the class files from the solution explorer onto the design surface. That's a bit lower fidelity, since it doesn't have all the data elements needed, but it'll get you most of the way there and you can tweak the class and property attributes in the designer to get what you want. 

If you had a compiled assembly, anything from EF6 to EFCore6, you could drop that assembly onto the design surface from the file explorer and get a more robust model, although you'll still need to tweak some things since not all modeler properties can be detected from the DbContext (and I'm sure there are some that could be detected but we just failed to do it :-) )

You can find more info at https://msawczyn.github.io/EFDesigner/Importing.html

Hope that helps.

**Comment by papyr** [comment]
Hello @msawczyn this is exactly what I was looking for, thanks for the explanation. Also the way you have it planned is very intuitive.



Option 1
When I drag `classes from the explorer view`, on the designer view the `cursor turns to null` preventing me from dragging anything onto the designer surface. (sometimes it asks for a xamarin firewall exception rule, not sure what thats about.)

Option 2:
If I `drag a class lib project `.NET core 2.1 with a model namespace, it claims circular dependency. I tried it with couple other projects as well with the same error.

Any ideas on how to get past this, please.

thanks

**Comment by sjh37** [comment]
@msawczyn  We got the same question :-)
https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/771

**Comment by papyr** [comment]
I was trying both tools @sjh37

**Comment by msawczyn** [comment]
Hi @papyr ,

I can't reproduce that. Using Visual Studio 2022 and v4.2.0.5 of the designer, I typed in the following class:

```c#
   public class TestClassForImport
   {
      public int Id { get; set; }
      public string FirstName { get; set; }
      public string LastName { get; set; }
      public DateOnly BirthDate { get; set; }
   }
```
That gave me a solution explorer that looked like
![image](https://user-images.githubusercontent.com/1778442/184817130-75a3623f-1da7-4ccd-85b8-0302c1ceb163.png)

I then opened the designer and dragged `TestClassForImport` from the solution explorer to the designer where I dropped it.
![image](https://user-images.githubusercontent.com/1778442/184817247-df826e9c-7965-4433-9dcd-8582a03bb44c.png)

Clicking `Yes` I got

![image](https://user-images.githubusercontent.com/1778442/184817307-5431cea5-4b00-435a-8563-a95885aaf589.png)

I got the same results by dragging the file from File Explorer to the design surface.

You're not getting the same results?

**Comment by papyr** [comment]
Hello @msawczyn thats exactly what I want to do, but its not dragging _on the designer surface_ it shows null /stop symbol while dragging over. I updated to latest, and when I try to screenshot I loose the _null/no drag/stop drag/icon_ cursor.

Is there anything I can do to help, I would love to help and contribute in some way 🛩️ 
- [ ] How can I setup a break point and run the debug version,
- [ ] Can I download the EFDesigner code and run it in debug/ what steps should I setup to run it in debug please? and where should I set the debug breakpoint to catch it.

Not sure how to debug a VSIX extn...

**Comment by papyr** [comment]
Finally, I was able to fix it after tinkering around, I think it has to do with hub process, I am testing it. I will try do a PR on the documentation to help people.
