### ISSUE TITLE
"Add new Property" missing on Entity

### ISSUE THREAD

**Issue by Mr-Pearce** [msawczyn/EFDesigner2022#3]
In Vs 2019 i could rightlick on Propertie of an Entity and "Add new Property"
![grafik](https://user-images.githubusercontent.com/13457314/143847892-8769f0ec-546a-40a3-83d7-d5235a04f518.png)
in 2022 i cant
![grafik](https://user-images.githubusercontent.com/13457314/143847948-21405c9c-33e5-4160-831a-123cae3b67e8.png)

**Comment by Kalle4242** [comment]
How did you install EFDesigner into VS2022?

**Comment by Mr-Pearce** [comment]
i installed the file from https://github.com/msawczyn/EFDesigner2022/tree/master/dist

**Comment by msawczyn** [comment]
This is a Visual Studio Modeling SDK issue. See https://developercommunity.visualstudio.com/t/DSL-Editor-context-menu-is-empty/1565770?space=8&q=dsl+context+menu+broken

According to that report, a fix has been implemented and will be released shortly. We're just going to have to wait on that, unfortunately.

**Comment by msawczyn** [comment]
Problem resolved by Microsoft in Visual Studio 17.1 preview 2, and confirmed to work in 17.1 preview 4. Will continue to monitor preview versions to make sure it stays fixed.
