### ISSUE TITLE
Support for Identity Model Customization

### ISSUE THREAD

**Issue by Mattnificent** [msawczyn/EFDesigner2022#31]
As described here:

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model

Not sure if this is possible - I tried this a few weeks ago, and just reverted everything back because I got caught in a snag.

I was able to add the attributes to my custom IdentityUser class, and context (fully qualified class names, since I don't see a way to add "using" statements to the generated context/model files)

The snag I ran into was that I couldn't specify the Primary Key for my inherited IdentityUser class in the EFDesign surface.  Maybe there's a way to monkeywrench this thing to work in the Fluent API of the custom context partial class?

Would be super cool!

**Comment by msawczyn** [comment]
Closing as duplicate of #38
