### ISSUE TITLE
When creating an Independent EFModel Class library/Project, its missing settings in context & EF core migrations fail.

### ISSUE THREAD

**Issue by fasteddys** [msawczyn/EFDesigner2022#43]
Been reading your docs a lot!! :)

I created an independent class lib in EF 6 (to keep this as clean as possible), and refer to the models from other projects. 

____________

![image](https://user-images.githubusercontent.com/96149622/187829699-c3c4fa90-6429-42d5-981f-405be05779e6.png)
this picture shows me, that I failed to add migrations. I assume its because there is a missing `connectionstring `in the `DBcontext`

![image](https://user-images.githubusercontent.com/96149622/187829813-80b49773-6a81-4c7e-88d5-03257b7408b8.png)

Question 1: `How do I get the EF designer 2k22 code gen to pick up the connection string?,` so it can be scaffolded into the DBcontext. And, where does it pick it up from, I even tried to add a `app.config` file with a new connection string, but its not picking it up... should I be doing this differently?

<?xml version="1.0" encoding="utf-8" ?>
<configuration>
	<connectionStrings>
		<add connectionString="defaultconnection" .../>
	</connectionStrings>
</configuration>

Question 2: From the model generated, **to create a new database** -> `am I correct in creating a new migration, using that I would create my Database? ` or how do I create the DB from the EF Designer Models?

**Comment by msawczyn** [comment]
1) You can add the connection string as a property of the designer surface. 
![image](https://user-images.githubusercontent.com/1778442/188273509-504108c1-39c1-4c96-b08b-1f876fae1462.png)
Click the design surface and these will appear in the property window. Note you can add either a connection string or a connection string name (with the connection string being stored in a config file somewhere else) and EFCore will be able to use it.

2) Generating the model gets you the entity classes and a DbContext -- from there you can create the migrations, use the context, etc. The EFCore docs talk about how the migrations can automatically create a database, how to update that structure, etc.

**Comment by fasteddys** [comment]
thanks
