### ISSUE TITLE
Removal of association does not remove the isForeignKeyFor value

### ISSUE THREAD

**Issue by alprinias** [msawczyn/EFDesigner2022#47]
Hi,

I had a bidirectional association between two tables and it happened that the Primary Key of the second one (Id) was also the Foreign Key for the first one. When I removed the association, the key icon was not removed from the property (see the attached image, the parent table is Incident, the child is Escape). Checking the model I saw that the isForeignKeyFor property had a value which was not pointing to anything in the model. When I replaced it with "00000-00..." the key icon disappeared.

Best,
Alex
![IncidentEscape](https://user-images.githubusercontent.com/8612300/194090066-638dfea2-5623-423d-af3b-e700e3622114.jpg)

**Comment by msawczyn** [comment]
Fixed in 4.2.2
