### ISSUE TITLE
ForenKey

### ISSUE THREAD

**Issue by Daniel-Gabriel-RJ** [msawczyn/EFDesigner2022#49]
How i set the ForeignKey name on Association , when i put the navigation name  , they  put my key name on the end , my forenkey have another name format

Example :
  .HasForeignKey("EmpresaCodigo"); must be Cod_empresa

![image](https://user-images.githubusercontent.com/115379037/195258071-5c353696-3633-4e1b-b0ab-52fd711f5336.png)

**Comment by msawczyn** [comment]
It's a property of the association
![image](https://user-images.githubusercontent.com/1778442/197577049-b100371a-6c63-4aae-978e-3b24b8743354.png)
