### ISSUE TITLE
Visual Designer 4.0.0.6 in VS2022 17.0.4 Problem with diagrams

### ISSUE THREAD

**Issue by AlexGoemanDigipolis** [msawczyn/EFDesigner2022#6]
In a newly installed VS2022 I installed Visual Designer 4.0.0.6

I tried a new project from scratch, and then I cannot create a seconds diagram. In the entity model explorer when I right click on the root node the popup menu contains almost no actions besides "Copy" and "Properties".
The default diagram works

When opening an existing model (created in VS2019) we get a COM error trying to open one of the extra diagrams

**Comment by AlexGoemanDigipolis** [comment]
can someone confirm this is a problem ?

**Comment by vvboborykin** [comment]
I got the same problem (can't create second diagram)

**Comment by msawczyn** [comment]
And neither can I :-(

It's a Microsoft issue with the Modeling SDK. I'm working on getting them the necessary data to track down and fix the problem. That's two errors so far ... the conversion to asynchronous-only extensions and 64-bit hasn't been kind to this SDK.
