### ISSUE TITLE
New release date

### ISSUE THREAD

**Issue by IoTFier** [msawczyn/EFDesigner2022#60]
Hi @msawczyn, how are you?

When do you plan to release the next release?

Thank you

**Comment by msawczyn** [comment]
Very soon now. Just getting a few loose ends (read: bugs) tidied up and the end-to-end testing finalized.

No firm date, unfortunately. Depends on how much I get piled on in my real job. It's been pretty busy for quite a while now.

**Comment by npagare** [comment]
Hello @msawczyn, how are you?
Will we be getting a new release soon?
I see the RC2 was ready in Feb of '24.
Thank you.
