### ISSUE TITLE
Image always stored with white background

### ISSUE THREAD

**Issue by msawczyn** [msawczyn/EFDesigner2022#62]
From a marketplace comment:

> Love your program. However, I'm trying to save a model as an image, and/or print it, and the background is all white. All of the connector lines are white, so they disappear, making the image/print pretty useless. Is there a way to set the background color? A way to set connector line color would also be nice. A simple color setting in the general Properties for the model would do, similar to the one for individual entities.

**Comment by vslee** [comment]
Is it possible to use reflection to call the private method?
