### ISSUE TITLE
Model Created in older versions can not run Generate Code

### ISSUE THREAD

**Issue by dongjason** [msawczyn/EFDesigner2022#67]
Hi,
Thank you so much for buidling such a wonderful tool. We have used it for over 5 years and it has really been a life saver.

After our recent upgrade to the V4.x, for some reason, it does not generate code on my existing model. Even though I removed all the classes, down to only one class, it still won't do so. When I click Generate Code, it says "Finished generating code from" immediately, but no files were generated.

I am attaching here the simplified model with only one class. Could you take a look at it and let me know if there is anything wrong?

Also, I downloaded the project source code and trying to do it locally, but the two DSL projects won't load. Is there an instruction for setting up the dev environment? Any other tools/extensions I need to add to VS?

Thanks
[EFmodel.zip](https://github.com/msawczyn/EFDesigner2022/files/11762117/EFmodel.zip)

**Comment by dongjason** [comment]
Hi, just following up to see if this can be resolved soon?  We really need this ASAP.  Thanks a lot.

BTW, is there any instruction to setup the development environment for the project on my own?  Thanks a lot.

**Comment by dongjason** [comment]
Hi, just following up to see if this can be resolved soon? We really need this ASAP. Thanks a lot.

**Comment by MichaelSawczyn-AWH** [comment]
I'm so sorry this took so long to get back to you.

I'm able to run the translation without problem, using v4.2.5.1.

I'd like you to try something for me.

In the project where the model lives, add these files:
[EFDesigner_Templates_v4.2.5.1.zip](https://github.com/msawczyn/EFDesigner2022/files/12329909/EFDesigner_Templates_v4.2.5.1.zip)

They'll be used in place of whatever you have installed. If this works for you, you're going to need to find where the tool is installed in the file system and in the registry ... something is pointing to the wrong place, and uninstalling may not completely fix it. 

To find the files in the file system:

- Using Explorer, navigate to the Visual Studio installation directory (mine is `C:\Program Files\Microsoft Visual Studio\2022\Enterprise`)
- Search for `EFModel.DslPackage` in the directories under that.
- In the directory you just found (mine was `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\03ieblfo.xji`) go to the `Templates` directory under that. The files there should match what's in the `.zip` above.
- If they don't you can overwrite them with the files from the included `.zip` file.

Let me know what you find.

-- Michael

**Comment by msawczyn** [comment]
I'm so sorry this took so long to get back to you.

I'm able to run the translation without problem, using v4.2.5.1.

I'd like you to try something for me.

In the project where the model lives, add these files:
[EFDesigner_Templates_v4.2.5.1.zip](https://github.com/msawczyn/EFDesigner2022/files/12329943/EFDesigner_Templates_v4.2.5.1.zip)

They'll be used in place of whatever you have installed. If this works for you, you're going to need to find where the tool is installed in the file system and in the registry ... something is pointing to the wrong place, and uninstalling may not completely fix it.

To find the files in the file system:

- Using Explorer, navigate to the Visual Studio installation directory (mine is `C:\Program Files\Microsoft Visual Studio\2022\Enterprise`)
- Search for `EFModel.DslPackage` in the directories under that.
- In the directory you just found (mine was `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\03ieblfo.xji`) go to the `Templates` directory under that. The files there should match what's in the `.zip` above.
- If they don't you can overwrite them with the files from the included `.zip` file.

Let me know what you find.

-- Michael

**Comment by msawczyn** [comment]
>  I downloaded the project source code and trying to do it locally, but the two DSL projects won't load. Is there an instruction for setting up the dev environment? Any other tools/extensions I need to add to VS?

Nothing except the [Visual Studio Modeling SDK](https://learn.microsoft.com/en-us/visualstudio/modeling/modeling-sdk-for-visual-studio-domain-specific-languages?view=vs-2022) is required to build the solution. All other dependencies are Nuget packages that are acquired at build time.

**Comment by msawczyn** [comment]
You can also try to step through the `.tt` file in debug to see which templates it's trying to load and from where. I believe you'll find that they're just not where it thinks they should be, which indicates something going wrong during installation or a problem with your registry.
