### ISSUE TITLE
HasQueryFilter Support

### ISSUE THREAD

**Issue by BlackPuddingERP** [msawczyn/EFDesigner2022#70]
Hello, first of all, congratulations on creating this incredibly useful and user-friendly tool. I find the effort and dedication you put into this project truly admirable.

I have a question, and I'm not sure how to proceed. I have a database table where we store two different types of objects with several common properties and a couple of distinct ones for each object. Let's say the table looks like this: Person -> Man // Person -> Woman, with Person being the abstract entity. The Person table has a property called "Type," which is of type char and indicates whether the record corresponds to a Man ('M') or a Woman ('W').

I noticed that in order to automatically filter the records for Men (Type = 'M') when querying the Person table, one needs to use HasQueryFilter, as shown in this [documentation](https://www.learnentityframeworkcore.com/configuration/fluent-api/hasqueryfilter-method).

My question is, does the designer support this? If not, do I have to manually put it in OnModelCreating?

Thank you very much.

**Comment by dongjason** [comment]
That seems to be a perfect situation where you would use the object inheritance.  You would use the inheritance connector in the EF Designer toolbox to connect from Person to Man/Woman class.  The EF Editor will generate the inheritance class and context code.  Check for the documentation site:
https://msawczyn.github.io/EFDesigner/index.html
https://msawczyn.github.io/EFDesigner/Inheritance.html.

**Comment by BlackPuddingERP** [comment]
Sorry, I thought it was understood that I was already implementing inheritance for both between person and man, and between person and woman. The issue is that whether you're a man or a woman, it's stored in the same table. So, when you retrieve values from the database with the context of 'man,' it also returns objects for women. That's why I need to do a pre-filtering based on the field that differentiates between male and female, in this case, the 'Type' field.
I hope I have explained myself better now.
Thank you!

**Comment by msawczyn** [comment]
Hi @BlackPuddingERP -

Don't think of these as tables -- think of them as objects. Entity Framework will do what you want for you. 

If you have the model
![image](https://github.com/msawczyn/EFDesigner2022/assets/1778442/abb5ff2c-eeec-43d4-91ba-3a0a71c5d7ae)

Then, to get a `List<>` of all the men as Person objects, 
`People.OfType<Man>().ToList()`

and you don't need the `Type` property at all.

I can see where this makes sense if you'll have different associations and/or properties in `Man` and `Woman`, but I'm struggling to see a real use case for this. Obviously, it's not my problem to solve, but just wanted to throw that out.

**Comment by BlackPuddingERP** [comment]
Ohh, that makes sense. I had no idea that could be done. Thank you so much for taking the time to clear up my doubt!
