### ISSUE TITLE
Feature request: enable or disable an entity property

### ISSUE THREAD

**Issue by mamift** [msawczyn/EFDesigner2022#74]
I have a model with a large entity with many properties (about 155+):

![image](https://github.com/msawczyn/EFDesigner2022/assets/2508444/e9df3ded-3d11-4a14-9744-090ca9d0fef0)

It would be good to have a feature that allows one to disable or enable an individual property such that:

- Disabling the property removes the code generated for that property, but does not remove the property information from the model (.efmodel) file
- Enabling the property would add that code back in when code is re-generated

**Comment by BlackPuddingERP** [comment]
Hello @mamift,

I've been thinking for a while about your proposal, and I don't see in which cases it could be useful when designing the database.
In what cases would this functionality be useful?
Wouldn't it work to set the `Persistent` property to `false` in the field's properties to make it not exist in the database?

Regards

**Comment by mamift** [comment]
Ah I did not know about that, and that comes close, as changing `Persistent` to **false** does get picked up by EF migrations, so I'll use that for now. 

I have a library where clients are constantly changing (an in-production app) which columns are in use and which aren't; there are about 150+ in use columns, but about 500+ that aren't. So in total the column count is about ~650.

I realise I can't just leave them sitting there unused as I'm getting awfully close to the [1024 column table limit in SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/maximum-capacity-specifications-for-sql-server?view=sql-server-ver16), so I need to remove columns from the table to stay under that limit. Thanks!

**Comment by mamift** [comment]
This solves my issue. Thanks.
