### ISSUE TITLE
How Create the Backend-Database (MS-SQL)

### ISSUE THREAD

**Issue by MyKeySoftMK** [msawczyn/EFDesigner2022#75]
I have found your fine projekct and design-tool.

But i didn´t find a way how can i create the Backend-DB with this tool. 

When I finished the work of the design, what I must do, to create the DB-Schema send to a MS-SQL Server (maybe if i install the application to the server)? I have read that EFCore have a mechanism to create and migrate DB-Schemas. But I didn´t konw how can i use it with you tool

**Comment by BlackPuddingERP** [comment]
This tool doesn't generate the database directly; what it does is generate the necessary classes and the DBContext that will be used later to generate the database.
To create the database, based on my experience (there may be some other way I'm not aware of), you need to do it using migrations, as you mentioned. This process is quite straightforward. You simply need to create an initial migration to generate the database. Let's assume we already have our database design completed, and now we want to generate the database. Here's what you do (see this [link](https://www.learnentityframeworkcore.com/migrations) for more info):

If you are in the "Package Manager Console" in Visual Studio, you run:
- `add-migration [<Migration Name>]`

If you are in the regular command prompt (in the project's directory), you run:
- `dotnet ef migrations add [<Migration Name>]`

The name can be a version (1.0.0) or anything that identifies the migration for you.
If this fails, it's possible that you're missing some dependencies in the project (I believe it's Microsoft.EntityFrameworkCore.Tools).

After running the command, it will create a 'Migrations' folder in the project's root directory with the necessary code to create the database.
Now, you have two options to generate the database:
1. Manually by executing the command via the console.
   - If you are in the "Package Manager Console" in Visual Studio, you run:
     - `Update-Database`
   - If you are in the regular command prompt (in the project's directory), you run:
     - `dotnet ef database update`
2. Check migrations programmatically, typically when the application starts.
   - For example, you can put the code in Program.cs.
      ```cs
      using (MyDbContext context = new())
      {
            context.Database.Migrate();
      }
      ```

Now, imagine that in the future, we've added a column to a table and changed the name of another column just to reflect those changes in the database. We simply generate another migration (without deleting the previous one), and if we had named the first one `1.0.0`, we can use something like `add-migration 1.0.1` and then follow the same procedure to update the database.

I hope this has helped you understand better.

**Comment by MyKeySoftMK** [comment]
Thank you for your reply - that had help me much to understand the process.

So i want to start with the inital generation for MS-SQL. But the first error is
''Unable to create an object of type 'FxCoreUsers'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728''

I think i missing some Properties to work fine - i have only put in "Connection String" in the .efmodel - but i didn´t find properties for which DB-System the Migration will be used (ex. MS-SQL)

**Comment by BlackPuddingERP** [comment]
To perform a migration, you need to be able to initialize the `DbContext` during design time. For this, I recommend enabling the `Generate Db Context Factory` option in the designer properties. This will assist in creating the necessary class for migration.

Once the `Factory` class is generated, in the `CreateDbContext` methods you will find a comment that explains what you need to do. Essentially, you need to create a partial class of the class that inherits from the context and add the necessary method to initialize the context.

```cs

public partial class [<DBContextClassName>]
{

    public static void ConfigureOptions(DbContextOptionsBuilder<[<DBContextClassName>]> optionsBuilder)
    {
        optionsBuilder.UseSqlServer(ConnectionString);
    }
}

```

I hope this helps.

**Comment by MyKeySoftMK** [comment]
Thank you - that informations what very helpfull and works fine
