### ISSUE TITLE
How generate a "timestamp" column/property

### ISSUE THREAD

**Issue by MyKeySoftMK** [msawczyn/EFDesigner2022#76]
My former DB-Design on MS-SQL has a "timestamp" column for the Property "Rowversion" - i use it for concurrency reason (is the value in this property different from that on DB, than the row is changed meanwhile)

What is the correct design with EFDesigner2022?

**Comment by BlackPuddingERP** [comment]
Honestly, I haven't understood your question.
If what you need is to implement concurrency, you can set the `Concurrency` property (in the table properties) to the value `Optimistic`.
If your question is different, please rephrase it for better understanding.
