### ISSUE TITLE
How design "Users To UserGroups"

### ISSUE THREAD

**Issue by MyKeySoftMK** [msawczyn/EFDesigner2022#77]
I have create the Entity "Users" and the Entity "UserGroups".

In my last project without EF i create a table with the name "UsersToUserGroups" and the colums "UserId" and "GroupId". The realation was: Users <= 1:many => UsersToUserGroups <= many:1 => UserGroups

Now I read your documentation and ask me: need i the "UsersToUserGroups"-Entity or do it EF that "behind"?

And another question: how define the columens that are the ForenKeys of the 1:many?

**Comment by BlackPuddingERP** [comment]
When creating a `many-to-many` relationship, the table you mentioned as `UsersToUserGroups` will be automatically generated by default with a name that, in your case, would be `Users_x_UserGroups`. This name can be changed from the relationship properties.

I don't quite understand your second question, but if you are asking about how to create relationships, while using the designer, open the tools panel and select the type of relationship you want by clicking on it. Then, you need to go to the entity that represents the `one` part of the 1:n relationship, click on it, and proceed to click on the entity that represents the `many` part.

![image](https://github.com/msawczyn/EFDesigner2022/assets/96109950/0dc61afa-a3c4-407a-a6c2-5a234aeb88ba)


This has nothing to do with your question, but I would recommend that table names be in singular.
