### ISSUE TITLE
Is it possible to add some inital data to the database?

### ISSUE THREAD

**Issue by MyKeySoftMK** [msawczyn/EFDesigner2022#78]
I have finished the schema design.

Is it possible to add some initial data to the concept?

Example: i will add a Usergroup "Administrators" and a User "Admin". This User should be in the Admin-Group. Can i add this data to the database when i execute "Update-Datase"

**Comment by msawczyn** [comment]
Please see https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli
