### ISSUE TITLE
How Generate a GUID as PK?

### ISSUE THREAD

**Issue by MyKeySoftMK** [msawczyn/EFDesigner2022#79]
By default a autoincrement int64 is set as PK for every Entity.

In my design i will use Guids as PK - so it easier to combine online/offline DB.

Now i set the property as follows:
Database Default Value: newid()
Identity Type: AutoFenerated
Type: Guid

Is it correct so? I missing in the created Table on the SQL-Server the 'newid()'-Command

**Comment by BlackPuddingERP** [comment]
Don't you think it doesn't make sense for the entity to be `Autogenerated` (created by the database) and at the same time try to create it yourself in the `Database default value`?

**Comment by msawczyn** [comment]
EFCore will take care of that for you. Please see https://learn.microsoft.com/en-us/ef/core/
