### ISSUE TITLE
CRUD Commands for Entities

### ISSUE THREAD

**Issue by MyKeySoftMK** [msawczyn/EFDesigner2022#80]
When i understand the concept of your Generator, than is that the "Model" of an MVVM-Concept.

My Class is named "DataAccess" and all the Entities are designed and generated. I only found the "Create"-Routine - but no Read, Update or Delete.

How can i generate them all in the DataAccess-Class? 

Did you have a example-application how can i see how you implementet your EFDesigner2022 in a "real-life" MAUI-App?

**Comment by msawczyn** [comment]
From the questions you're posting, I believe you have a fundamental misunderstanding of Entity Framework and what this tool can do. The designer is only an extension to Visual Studio to make creating EFCore (and EF6) code easier to write. For Entity Framework background, please see https://learn.microsoft.com/en-us/ef/core/
